version: '3.3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_user_password
      - MYSQL_DATABASE=/run/secrets/mysql_user_database
      - MYSQL_USER=/run/secrets/mysql_user_name
    secrets:
      - mysql_root_password
      - mysql_user_password
      - mysql_user_name
      - mysql_user_database

  app:
    image: nextcloud:21.0.0-apache
    restart: always
    volumes:
      - ./data/nextcloud:/var/www/html
      - ./data/app/config:/var/www/html/config
      - ./data/app/custom_apps:/var/www/html/custom_apps
      - ./data/app/data:/var/www/html/data
      - ./data/app/themes:/var/www/html/themes
    environment:
      - VIRTUAL_HOST=${DOM_BASE:-localhost}
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOM_BASE:-localhost}
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_user_password
      - MYSQL_DATABASE=/run/secrets/mysql_user_database
      - MYSQL_USER=/run/secrets/mysql_user_name
      - MYSQL_HOST=db
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - mysql_user_password
      - mysql_user_name
      - mysql_user_database
    depends_on:
      - db
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certs:/etc/nginx/certs:ro
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - omgwtfssl

  omgwtfssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - ./data/certs:/certs
    environment:
      - SSL_SUBJECT=${DOM_BASE:-localhost}
      - CA_SUBJECT=Sergey Kovalev
      - SSL_KEY=/certs/${DOM_BASE:-localhost}.key
      - SSL_CSR=/certs/${DOM_BASE:-localhost}.csr
      - SSL_CERT=/certs/${DOM_BASE:-localhost}.crt
      - CA_EXPIRE=365
    networks:
      - proxy-tier

  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /data/plex/config:/config
      - /tvseries:/tv
      - /movies:/movies
    restart: always

  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /data/calibre/config:/config
      - /data/calibre/books:/books
    ports:
      - 8085:8083
    restart: always
    networks:
      - default

  kerberos-cam1:
    image: kerberos/kerberos
    restart: always
    ports:
      - 8081:80
    #environment:
    #  - VIRTUAL_HOST=${DOM_KERBEROS_CAM_1:-localhost}
    volumes:
      - ./secrets/mailrc:/mailrc
      - ./data/kerberos/cam1/config:/etc/opt/kerberosio/config
      - ./data/kerberos/cam1/capture:/etc/opt/kerberosio/capture
      - ./data/kerberos/cam1/logs:/etc/opt/kerberosio/logs
      - ./data/kerberos/cam1/web:/var/www/web/config
    networks:
    #  - proxy-tier
      - default

  kerberos-cam2:
    image: kerberos/kerberos
    restart: always
    ports:
      - 8082:80
    #environment:
    #  - VIRTUAL_HOST=${DOM_KERBEROS_CAM_1:-localhost}
    volumes:
      - ./secrets/mailrc:/mailrc
      - ./data/kerberos/cam2/config:/etc/opt/kerberosio/config
      - ./data/kerberos/cam2/capture:/etc/opt/kerberosio/capture
      - ./data/kerberos/cam2/logs:/etc/opt/kerberosio/logs
      - ./data/kerberos/cam2/web:/var/www/web/config
    networks:
    #  - proxy-tier
      - default

networks:
  proxy-tier:

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password
  mysql_user_password:
    file: ./secrets/mysql_user_password
  mysql_user_name:
    file: ./secrets/mysql_user_name
  mysql_user_database:
    file: ./secrets/mysql_user_database
  nextcloud_admin_password:
    file: ./secrets/nextcloud_admin_password
  nextcloud_admin_user:
    file: ./secrets/nextcloud_admin_user
