version: '3.3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_user_password
      - MYSQL_DATABASE=/run/secrets/mysql_user_database
      - MYSQL_USER=/run/secrets/mysql_user_name
    secrets:
      - mysql_root_password
      - mysql_user_password
      - mysql_user_name
      - mysql_user_database

  app:
    image: nextcloud:21.0.0-apache
    restart: always
    volumes:
      - ./data/nextcloud:/var/www/html
      - ./data/app/config:/var/www/html/config
      - ./data/app/custom_apps:/var/www/html/custom_apps
      - ./data/app/data:/var/www/html/data
      - ./data/app/themes:/var/www/html/themes
      - /media/abooks:/media/abooks
      - /media/books:/media/books
      - /media/data:/media/data
      - /media/documents:/media/documents
      - /media/downloads:/media/downloads
      - /media/movies:/media/movies
      - /media/music:/media/music
      - /media/photo:/media/photo
      - /media/tvseries:/media/tvseries
      - /media/video-tutorials:/media/tutorials
    environment:
      - VIRTUAL_HOST=${DOM_NEXTCLOUD_IP:-localhost}
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOM_NEXTCLOUD_IP:-localhost}
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_user_password
      - MYSQL_DATABASE=/run/secrets/mysql_user_database
      - MYSQL_USER=/run/secrets/mysql_user_name
      - MYSQL_HOST=db
      - PUID=1000
      - PGID=1000
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - mysql_user_password
      - mysql_user_name
      - mysql_user_database
    depends_on:
      - db
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certs:/etc/nginx/certs:ro
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - omgwtfssl

  omgwtfssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - ./data/certs:/certs
    environment:
      - SSL_SUBJECT=${DOM_NEXTCLOUD_IP:-localhost}
      - CA_SUBJECT=Sergey Kovalev
      - SSL_KEY=/certs/${DOM_NEXTCLOUD_IP:-localhost}.key
      - SSL_CSR=/certs/${DOM_NEXTCLOUD_IP:-localhost}.csr
      - SSL_CERT=/certs/${DOM_NEXTCLOUD_IP:-localhost}.crt
      - CA_EXPIRE=365
    networks:
      - proxy-tier

  emby:
    image: ghcr.io/linuxserver/emby
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - ./data/emby/config:/config
      - /media/abooks:/data/abooks
      - /media/movies:/data/movies
      - /media/music:/data/music
      - /media/tvseries:/data/tvshows
      - /media/video-tutorials:/data/tutorials
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8096:8096
      - 8920:8920
    devices:
      - /dev/dri:/dev/dri
    restart: always

  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - DOCKER_MODS=linuxserver/calibre-web:calibre
      - /etc/localtime:/etc/localtime:ro
    volumes:
      - /.data/calibre/config:/config
      - /media/books:/books
    ports:
      - 8083:8083
    restart: always

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - WEBUI_PORT=8080
    volumes:
      - ./data/qbittorrent/config:/config
      - /media/abooks:/data/abooks
      - /media/downloads:/downloads
      - /media/movies:/data/movies
      - /media/music:/media/music
      - /media/tvseries:/data/tvshows
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8084:8080
    restart: always

  motioneye:
    image: ccrisan/motioneye:master-amd64
    ports:
      - "8765:8765"
    environment:
      - TG_BOT_FILE=/run/secrets/tg_bot
      - TG_CHAT_FILE=/run/secrets/tg_surveillance_chat
    volumes:
      - ./data/motioneye/etc:/etc/motioneye
      - ./data/motioneye/videos:/var/lib/motioneye
      - ./scripts:/scripts
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - tg_bot
      - tg_surveillance_chat
    restart: always

networks:
  proxy-tier:

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password
  mysql_user_password:
    file: ./secrets/mysql_user_password
  mysql_user_name:
    file: ./secrets/mysql_user_name
  mysql_user_database:
    file: ./secrets/mysql_user_database
  nextcloud_admin_password:
    file: ./secrets/nextcloud_admin_password
  nextcloud_admin_user:
    file: ./secrets/nextcloud_admin_user
  tg_surveillance_chat:
    file: ./secrets/tg_surveillance_chat
  tg_bot:
    file: ./secrets/tg_bot