version: '3.3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_user_password
      - MYSQL_DATABASE=/run/secrets/mysql_user_database
      - MYSQL_USER=/run/secrets/mysql_user_name
    secrets:
      - mysql_root_password
      - mysql_user_password
      - mysql_user_name
      - mysql_user_database

  app:
    image: nextcloud:21.0.0-apache
    restart: always
    volumes:
      - ./data/nextcloud:/var/www/html
      - ./data/app/config:/var/www/html/config
      - ./data/app/custom_apps:/var/www/html/custom_apps
      - ./data/app/data:/var/www/html/data
      - ./data/app/themes:/var/www/html/themes
      - /media/abooks:/media/abooks
      - /media/books:/media/books
      - /media/data:/media/data
      - /media/documents:/media/documents
      - /media/downloads:/media/downloads
      - /media/movies:/media/movies
      - /media/music:/media/music
      - /media/photo:/media/photo
      - /media/tvseries:/media/tvseries
      - /media/video-tutorials:/media/tutorials
    environment:
      - VIRTUAL_HOST=${DOM_NEXTCLOUD_IP:-localhost}
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOM_NEXTCLOUD_IP:-localhost}
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_user_password
      - MYSQL_DATABASE=/run/secrets/mysql_user_database
      - MYSQL_USER=/run/secrets/mysql_user_name
      - MYSQL_HOST=db
      - PUID=1000
      - PGID=1000
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - mysql_user_password
      - mysql_user_name
      - mysql_user_database
    depends_on:
      - db
      - calibre-web
      - kerberos-cam1
      - kerberos-cam2
      - plex
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certs:/etc/nginx/certs:ro
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - omgwtfssl

  omgwtfssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - ./data/certs:/certs
    environment:
      - SSL_SUBJECT=${DOM_NEXTCLOUD_IP:-localhost}
      - CA_SUBJECT=Sergey Kovalev
      - SSL_KEY=/certs/${DOM_NEXTCLOUD_IP:-localhost}.key
      - SSL_CSR=/certs/${DOM_NEXTCLOUD_IP:-localhost}.csr
      - SSL_CERT=/certs/${DOM_NEXTCLOUD_IP:-localhost}.crt
      - CA_EXPIRE=365
    networks:
      - proxy-tier

  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      #- VIRTUAL_HOST=${DOM_PLEX:-localhost}
      #- VIRTUAL_PORT=32400
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /data/plex/config:/config
      - /tvseries:/tv
      - /movies:/movies
    restart: always

  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      #- VIRTUAL_HOST=${DOM_CALIBRE:-localhost}
      #- VIRTUAL_PORT=8083
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /data/calibre/config:/config
      - /media/books:/books
    ports:
      - 8083:8083
    restart: always

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - WEBUI_PORT=80
    volumes:
      - /path/to/appdata/config:/config
      - /path/to/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8084:80
    restart: always

  kerberos-cam1:
    build: ./kerberos
    restart: always
    ports:
      - 8081:80
    #environment:
    #  - VIRTUAL_HOST=${DOM_KERBEROS_CAM1:-localhost}
    volumes:
      - ./secrets/ssmtp:/etc/ssmtp
      - ./data/kerberos/cam1/config:/etc/opt/kerberosio/config
      - ./data/kerberos/cam1/capture:/etc/opt/kerberosio/capture
      - ./data/kerberos/cam1/logs:/etc/opt/kerberosio/logs
      - ./data/kerberos/cam1/web:/var/www/web/config
    secrets:
      - kerberos_default_mail

  kerberos-cam2:
    build: ./kerberos
    restart: always
    ports:
      - 8082:80
    #environment:
    #  - VIRTUAL_HOST=${DOM_KERBEROS_CAM2:-localhost}
    volumes:
      - ./secrets/ssmtp:/etc/ssmtp
      - ./data/kerberos/cam2/config:/etc/opt/kerberosio/config
      - ./data/kerberos/cam2/capture:/etc/opt/kerberosio/capture
      - ./data/kerberos/cam2/logs:/etc/opt/kerberosio/logs
      - ./data/kerberos/cam2/web:/var/www/web/config
    secrets:
      - kerberos_default_mail

networks:
  proxy-tier:

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password
  mysql_user_password:
    file: ./secrets/mysql_user_password
  mysql_user_name:
    file: ./secrets/mysql_user_name
  mysql_user_database:
    file: ./secrets/mysql_user_database
  nextcloud_admin_password:
    file: ./secrets/nextcloud_admin_password
  nextcloud_admin_user:
    file: ./secrets/nextcloud_admin_user
  kerberos_default_mail:
    file: ./secrets/kerberos_default_mail
